version: "3.7"

services:
  pia_transmission:
    image: haugene/transmission-openvpn
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun"
    container_name: pia_transmission
    restart: always
    ports:
      - "9091:9091"
      - "8888:8888"
      - "8989:8989" #sonarr
      - "9117:9117" #jackett
      - "7878:7878" #radarr
      - "7979:7979" #radarr-4k
      - "8686:8686" #lidarr
      - "8787:8787" #readarr
      - "9696:9696" #prowlarr
      - "8080:8080" #sabnzbd
      #- "5299:5299" #lazyLib
    dns:
      - 8.8.8.8
      - 8.8.4.4
    networks:
      - media_server
    env_file:
      - .env_openvpn
    volumes:
      - /mnt/trueNas/nfs/plex/appdata/transmission/:/config
      - /mnt/trueNas/Media/server/downloads:/data/downloads
      - /mnt/trueNas/Media/server/watch/:/watch

  jackett:
    image: linuxserver/jackett
    container_name: jackett
    depends_on:
      - pia_transmission
    restart: always
    env_file:
      - .env
    volumes:
      - /mnt/trueNas/nfs/plex/appdata/jackett/:/config
      - /mnt/trueNas/Media/server/watch/:/downloads
      - /etc/localtime:/etc/localtime:ro
    network_mode: "service:pia_transmission"
    #depends_on:
    #  - "pia_transmission"

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    volumes:
      - /mnt/trueNas/nfs/plex/appdata/sonarr/:/config
      - /mnt/trueNas/Media/TV Shows/:/tv
      - /mnt/trueNas/Media/server/:/downloads
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    restart: unless-stopped
    network_mode: "service:pia_transmission"
    depends_on:
      - "pia_transmission"

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=$TZ
    volumes:
      - /mnt/trueNas/nfs/plex/appdata/radarr:/config
      - /mnt/trueNas/Media/Movies:/movies
      - /mnt/trueNas/Media/server/:/downloads
      - /etc/localtime:/etc/localtime:ro
    #env_file:
    #  - .env
    restart: unless-stopped
    network_mode: "service:pia_transmission"
    depends_on:
      - "pia_transmission"

  radarr-4k:
    image: linuxserver/radarr
    container_name: radarr-4k
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=$TZ
    volumes:
      - /mnt/trueNas/nfs/plex/appdata/radarr-4k:/config
      - /mnt/trueNas/Media/Movies-4K:/movies
      - /mnt/trueNas/Media/server/:/downloads
      - /etc/localtime:/etc/localtime:ro
    #env_file:
    #  - .env
    restart: unless-stopped
    network_mode: "service:pia_transmission"
    depends_on:
      - "pia_transmission"
    #need to go to .../appdata/radarr-4k/config.xml and edit the port number to 7979:7979, instance name = Radarr-4k

  lidarr:
    image: linuxserver/lidarr
    container_name: lidarr
    volumes:
      - /mnt/trueNas/nfs/plex/appdata/lidarr/:/config
      - /mnt/trueNas/Media/Music/:/music
      - /mnt/trueNas/Media/server/downloads/completed/:/data/complete/
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    restart: unless-stopped
    network_mode: "service:pia_transmission"
    depends_on:
      - "pia_transmission"

#  lazylibrarian:
#    image: linuxserver/lazylibrarian
#    container_name: lazylibrarian
#    env_file:
#      - .env
#    volumes:
#      - /mnt/trueNas/nfs/plex/appdata/:/config
#      - /media/content/downloads/completed:/data/completed
#      - /media/content/Books/:/books
#      - /media/content/Audioooks/:/audiobooks
#    restart: unless-stopped
#    network_mode: "service:pia_transmission"
#    depends_on:
#      - "pia_transmission"

  readarr:
    image: ghcr.io/linuxserver/readarr:nightly 
    container_name: readarr
    volumes:
      - /mnt/trueNas/nfs/plex/appdata/readarr/:/config
      - /media/content/Books/:/books
      - /media/content/downloads/completed:/data/completed
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    restart: unless-stopped
    network_mode: "service:pia_transmission"
    depends_on:
      - "pia_transmission"

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:nightly
    container_name: prowlarr
    depends_on:
      - pia_transmission
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - /opt/prowlarr/:/config
    network_mode: "service:pia_transmission"
    #depends_on:
    #  - "pia_transmission"

  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=$TZ
    volumes:
      - /mnt/trueNas/nfs/plex/appdata/sabnzbd/:/config
      - /mnt/trueNas/Media/server/downloads:/data/downloads #optional
    #  - /mnt/trueNas/Media/server/downloads/incomplete:/incomplete-downloads #optional
      - /mnt/trueNas/Media/server/watch/:/watch
    restart: unless-stopped
    network_mode: "service:pia_transmission"
    depends_on:
      - "pia_transmission"

#  plex:
#    image: lscr.io/linuxserver/plex:latest
#    container_name: plex
#    network_mode: host
#    env_file:
#      - .env
#    volumes:
#      - /opt/plex:/config
#      - /media/content/TV:/tv
#      - /media/content/Movies:/movies
#      - /media/content/Music/:/music
#      - /media/content/Books/:/books
#      - /media/content/Photos/:/photos
#      - /media/content/Other/:/other
#    restart: unless-stopped
#    depends_on:
#      - "pia_transmission"

networks:
  media_server:
    driver: bridge
