version: "3.7"

## Sonarr
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /mnt/trueNas/nfs/plex/appdata/sonarr/:/config
      - /mnt/trueNas/Media/TV Shows/:/tv
      - /mnt/trueNas/Media/server/downloads/:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped