version: "3.7"

## Sonarr
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=$TZ
    volumes:
      - $CONFIGDIR/sonarr/:/config
      - $MEDIADIR/TV Shows/:/tv
      - $DOWNLOADSDIR/:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped

## Radarr
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=$TZ
    volumes:
      - $CONFIGDIR/radarr:/config
      - $MEDIADIR/Movies:/movies #optional
      - $DOWNLOADSDIR/:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped

## Jackett
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=$TZ
      - AUTO_UPDATE=true #optional
      - RUN_OPTS= #optional
    volumes:
      - $CONFIGDIR/jackett:/config
      - $WATCHDIR/:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped